# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pyllm_pb2 as pyllm__pb2


class pyLLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResponse = channel.unary_stream(
                '/pyLLMService/GenerateResponse',
                request_serializer=pyllm__pb2.LLMRequest.SerializeToString,
                response_deserializer=pyllm__pb2.LLMResponse.FromString,
                )


class pyLLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_pyLLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=pyllm__pb2.LLMRequest.FromString,
                    response_serializer=pyllm__pb2.LLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pyLLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class pyLLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pyLLMService/GenerateResponse',
            pyllm__pb2.LLMRequest.SerializeToString,
            pyllm__pb2.LLMResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
