# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyllm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpyllm.proto\"4\n\nLLMRequest\x12\x12\n\nbirth_date\x18\x01 \x01(\t\x12\x12\n\nbirth_time\x18\x02 \x01(\t\"\x1c\n\x0bLLMResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\t2?\n\x0cpyLLMService\x12/\n\x10GenerateResponse\x12\x0b.LLMRequest\x1a\x0c.LLMResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyllm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LLMREQUEST']._serialized_start=15
  _globals['_LLMREQUEST']._serialized_end=67
  _globals['_LLMRESPONSE']._serialized_start=69
  _globals['_LLMRESPONSE']._serialized_end=97
  _globals['_PYLLMSERVICE']._serialized_start=99
  _globals['_PYLLMSERVICE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
