// Code generated by trpc-go/trpc-cmdline v1.0.0. DO NOT EDIT.
// source: admin.proto

package proto

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AdminService defines service.
type AdminService interface {
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
}

func AdminService_Login_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &LoginRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminService).Login(ctx, reqbody.(*LoginRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AdminServiceServer_ServiceDesc descriptor for server.RegisterService.
var AdminServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.llyb.backend.admin.AdminService",
	HandlerType: ((*AdminService)(nil)),
	Methods: []server.Method{
		{
			Name: "/admin/login",
			Func: AdminService_Login_Handler,
		},
		{
			Name: "/trpc.llyb.backend.admin.AdminService/Login",
			Func: AdminService_Login_Handler,
		},
	},
}

// RegisterAdminService registers service.
func RegisterAdminService(s server.Service, svr AdminService) {
	if err := s.Register(&AdminServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AdminService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAdminService struct{}

func (s *UnimplementedAdminService) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, errors.New("rpc Login of service AdminService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AdminServiceClientProxy defines service client proxy
type AdminServiceClientProxy interface {
	Login(ctx context.Context, req *LoginRequest, opts ...client.Option) (rsp *LoginResponse, err error)
}

type AdminServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAdminServiceClientProxy = func(opts ...client.Option) AdminServiceClientProxy {
	return &AdminServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AdminServiceClientProxyImpl) Login(ctx context.Context, req *LoginRequest, opts ...client.Option) (*LoginResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/admin/login")
	msg.WithCalleeServiceName(AdminServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AdminService")
	msg.WithCalleeMethod("Login")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &LoginResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
