// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: admin.proto

package proto

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AdminService defines service.
type AdminService interface {
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
	// Register Register a new account with username + password.
	Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error)
	// Reasoning Basic "reasoning" endpoint used by the front-end "基础推理" page.
	Reasoning(ctx context.Context, req *ReasoningRequest) (*ReasoningResponse, error)
}

func AdminService_Login_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &LoginRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminService).Login(ctx, reqbody.(*LoginRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AdminService_Register_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RegisterRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminService).Register(ctx, reqbody.(*RegisterRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AdminService_Reasoning_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReasoningRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminService).Reasoning(ctx, reqbody.(*ReasoningRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AdminServer_ServiceDesc descriptor for server.RegisterService.
var AdminServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.llyb.backend.admin.Admin",
	HandlerType: ((*AdminService)(nil)),
	Methods: []server.Method{
		{
			Name: "/admin/login",
			Func: AdminService_Login_Handler,
		},
		{
			Name: "/admin/register",
			Func: AdminService_Register_Handler,
		},
		{
			Name: "/admin/reasoning",
			Func: AdminService_Reasoning_Handler,
		},
		{
			Name: "/trpc.llyb.backend.admin.Admin/Login",
			Func: AdminService_Login_Handler,
		},
		{
			Name: "/trpc.llyb.backend.admin.Admin/Register",
			Func: AdminService_Register_Handler,
		},
		{
			Name: "/trpc.llyb.backend.admin.Admin/Reasoning",
			Func: AdminService_Reasoning_Handler,
		},
	},
}

// RegisterAdminService registers service.
func RegisterAdminService(s server.Service, svr AdminService) {
	if err := s.Register(&AdminServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Admin register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAdmin struct{}

func (s *UnimplementedAdmin) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, errors.New("rpc Login of service Admin is not implemented")
}

// Register Register a new account with username + password.
func (s *UnimplementedAdmin) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, errors.New("rpc Register of service Admin is not implemented")
}

// Reasoning Basic "reasoning" endpoint used by the front-end "基础推理" page.
func (s *UnimplementedAdmin) Reasoning(ctx context.Context, req *ReasoningRequest) (*ReasoningResponse, error) {
	return nil, errors.New("rpc Reasoning of service Admin is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AdminClientProxy defines service client proxy
type AdminClientProxy interface {
	Login(ctx context.Context, req *LoginRequest, opts ...client.Option) (rsp *LoginResponse, err error)
	// Register Register a new account with username + password.
	Register(ctx context.Context, req *RegisterRequest, opts ...client.Option) (rsp *RegisterResponse, err error)
	// Reasoning Basic "reasoning" endpoint used by the front-end "基础推理" page.
	Reasoning(ctx context.Context, req *ReasoningRequest, opts ...client.Option) (rsp *ReasoningResponse, err error)
}

type AdminClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAdminClientProxy = func(opts ...client.Option) AdminClientProxy {
	return &AdminClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AdminClientProxyImpl) Login(ctx context.Context, req *LoginRequest, opts ...client.Option) (*LoginResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/admin/login")
	msg.WithCalleeServiceName(AdminServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Admin")
	msg.WithCalleeMethod("Login")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &LoginResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AdminClientProxyImpl) Register(ctx context.Context, req *RegisterRequest, opts ...client.Option) (*RegisterResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/admin/register")
	msg.WithCalleeServiceName(AdminServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Admin")
	msg.WithCalleeMethod("Register")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RegisterResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AdminClientProxyImpl) Reasoning(ctx context.Context, req *ReasoningRequest, opts ...client.Option) (*ReasoningResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/admin/reasoning")
	msg.WithCalleeServiceName(AdminServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Admin")
	msg.WithCalleeMethod("Reasoning")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReasoningResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
